### ISSUE TITLE
Using specific types in generated tuples

### ISSUE THREAD

**Issue by thmsndk** [adventureland-community/typed-adventureland#11]
Currently we generate the following interface for GDismantle
```ts
export interface GDismantle {
  items: Array<[number, string]>;
  cost: number;
}
```

but the items array was manually typed like this
```ts
export interface GDismantle {
  items: Array<[number, ItemsKey]>;
  cost: number;
}
```

How do we use specific types, the correct places in the generated types?

One idea I had was to simply override the type via the config and `"overrides"`
for example this
```json
"overrides": {
    "items" : "Array<[number, ItemsKey]>"
}
```

Another way would be to somehow infer the used values at the specified index and then map it to an existing type. "hardcoding" it in the config file seems like the easy solution for now.

The next problem becomes how to import  the `ItemsKey` type from the correct place. we could simply hardcode it via inline imports. e.g.
```json
"overrides": {
    "items" : "Array<[number, import('./items').ItemsKey]>"
}
```

else we need some sort of lookup map to find the correct import statement.

Lets discuss how we want to solve it.

**Comment by Telokis** [comment]
Here is what I think we could do:
- The **analysis** step should store strings values.
- `generateStringUnions` should take the analysis and register unions defined in `extractedTypes`.
- `generateStringUnions` should take the analysis and register the `xxxKey` unions.
- The registered unions should contain the name, the possible values and a way to reconstruct the path to its generated file.
- `generateStringUnions` should be executed for all `G.xyz` before moving on.
- Our `typeToTs` should handle `"string"` types differently:
  - We iterate over all registered string unions.
  - If all values for the `string` are found in an union, the type is transformed from `string` to `union`.
  - Otherwise, we keep a string.
- If the type is `union`, we should register that we might have a file to include (if different).

Question: Where are the unions outputted?  
Maybe we store the category we got the values from? (All `wtype` values will be found in the `Weapon` analysis so it should probably be outputted there.)  
How do we behave if values span multiple files? Is it even possible? Let's throw an error for now since we're not sure it's possible.
